[theme]
primaryColor = "#FF4B4B"  # Cor principal (botões, seleções)
backgroundColor = "#1E1E1E"  # Cor de fundo da aplicação
secondaryBackgroundColor = "#292929"  # Cor de fundo da barra lateral
textColor = "#FFFFFF"  # Cor do texto
font = "sans serif"  # Fonte do texto